# Generated by Django 5.2 on 2025-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=255)),
                ('MatKhau', models.CharField(max_length=50)),
                ('Quyen', models.CharField(max_length=50)),
                ('NgayTao', models.DateField()),
                ('otp', models.CharField(max_length=6)),
                ('verOtp', models.CharField(max_length=6)),
            ],
        ),
    ]
