# Generated by Django 5.1.7 on 2025-05-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=250)),
                ('ThuTu', models.IntegerField()),
                ('Diem', models.IntegerField()),
            ],
            options={
                'db_table': 'BaiHoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=50)),
                ('NgayTao', models.DateField(auto_now_add=True)),
                ('DiemLenCap', models.IntegerField()),
            ],
            options={
                'db_table': 'Khoahoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nguoidung', models.IntegerField(db_column='id_nguoidung')),
                ('id_baihoc', models.IntegerField(db_column='id_baihoc')),
                ('ngayLam', models.DateField(db_column='ngayLam')),
                ('ketQua', models.IntegerField(db_column='ketQua')),
            ],
            options={
                'db_table': 'OnTap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TienTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_khoahoc', models.IntegerField(db_column='id_khoahoc')),
                ('diem_tong', models.IntegerField(db_column='DiemTong')),
                ('tuvung_hoc', models.IntegerField(db_column='TuDaHoc')),
            ],
            options={
                'db_table': 'TienTrinh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TuVung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tu', models.CharField(max_length=255)),
                ('Dich', models.TextField()),
                ('PhatAm', models.CharField(blank=True, max_length=255, null=True)),
                ('HinhAnh', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TuVung',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'managed': False},
        ),
    ]
