# Generated by Django 5.1.7 on 2025-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_baihoc_khoahoc_ontap_tientrinh_tuvung_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nguoidung',
            table='NguoiDung',
        ),
    ]
