# Generated by Django 5.1.7 on 2025-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baihoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tieude', models.CharField(blank=True, db_column='TieuDe', max_length=250)),
                ('thutu', models.IntegerField(blank=True, db_column='ThuTu')),
                ('diem', models.IntegerField(blank=True, db_column='Diem')),
            ],
            options={
                'db_table': 'BaiHoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doithoai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tieude', models.CharField(blank=True, db_column='TieuDe', max_length=255)),
                ('muctieu', models.CharField(blank=True, db_column='MucTieu', max_length=255)),
                ('hinhanh', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'DoiThoai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dtnguoidung',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tinnhan', models.CharField(blank=True, db_column='TinNhan', max_length=255)),
                ('ngay', models.DateField(blank=True, db_column='Ngay')),
            ],
            options={
                'db_table': 'DTNguoiDung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khoahoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=50)),
                ('ngaytao', models.DateField(blank=True, db_column='NgayTao')),
                ('diemlencap', models.IntegerField(blank=True, db_column='DiemLenCap')),
            ],
            options={
                'db_table': 'Khoahoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, db_column='Ten', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255)),
                ('matkhau', models.CharField(blank=True, db_column='MatKhau', max_length=50)),
                ('quyen', models.CharField(blank=True, db_column='Quyen', max_length=50)),
                ('ngaytao', models.DateField(blank=True, db_column='NgayTao')),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('verotp', models.CharField(blank=True, db_column='verOtp', max_length=6)),
            ],
            options={
                'db_table': 'NguoiDung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ontap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ngaylam', models.DateField(blank=True, db_column='ngayLam')),
                ('ketqua', models.IntegerField(blank=True, db_column='ketQua')),
            ],
            options={
                'db_table': 'OnTap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thoai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cauhoi', models.CharField(blank=True, db_column='Cauhoi', max_length=255)),
                ('ngaytao', models.DateField(blank=True, db_column='NgayTao')),
            ],
            options={
                'db_table': 'Thoai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tientrinh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diemtong', models.IntegerField(blank=True, db_column='DiemTong')),
                ('tudahoc', models.IntegerField(blank=True, db_column='TuDaHoc')),
            ],
            options={
                'db_table': 'TienTrinh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traloi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ngaygui', models.DateField(blank=True, db_column='NgayGui')),
                ('noidung', models.CharField(blank=True, db_column='NoiDung', max_length=255)),
            ],
            options={
                'db_table': 'TraLoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuvung',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tu', models.CharField(blank=True, db_column='Tu', max_length=255)),
                ('dich', models.CharField(blank=True, db_column='Dich', max_length=255)),
                ('phatam', models.CharField(blank=True, db_column='PhatAm', max_length=255)),
                ('hinhanh', models.CharField(blank=True, db_column='HinhAnh', max_length=255)),
            ],
            options={
                'db_table': 'TuVung',
                'managed': False,
            },
        ),
    ]
