# Generated by Django 5.1.7 on 2025-05-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doithoai',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dtnguoidung',
            options={'managed': True},
        ),
    ]
