# Generated by Django 5.1.7 on 2025-05-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_doithoai_options_alter_dtnguoidung_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doithoai',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dtnguoidung',
            options={'managed': False},
        ),
    ]
